name: Deploy to Production environment

on:
  push:
    branches:
      - master

jobs:
  prod-deploy:
    name: prod-deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: chrislennon/action-aws-cli@v1.1

      - name: Set AWS region
        run: aws configure set region ap-northeast-1

      - name: Run AWS CodeDeploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws deploy create-deployment --application-name "scenepicks-prod-deploy" --deployment-group-name "scenepicks-ec2-prod" --file-exists-behavior "OVERWRITE" --github-location repository="shortintern2020-C-cryptograph/TeamF",commitId=$GITHUB_SHA