name: Golang Test

on:
  pull_request:
    branches:
      - development

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  server-test:
    name: Server Test
    needs: prepare
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go get -v -t -d ./server

      - name: Get jsondiff
        run: go get github.com/Cside/jsondiff

      - name: Get go-shellwords
        run: go get github.com/mattn/go-shellwords

      - name: Run docker-compose # テスト実行用にdockerを起動
        run: make docker/run

      - name: Test code
        run: go test -v ./server/handler

      - name: Stop docker-compose
        run: make docker/stop