name: Build and Push

on:
  push:
    branches:
      - staging

jobs:
  server-test:
    name: Server Test
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go get -v -t -d ./server

      - name: Get jsondiff
        run: go get github.com/Cside/jsondiff

      - name: Get go-shellwords
        run: go get github.com/mattn/go-shellwords

      - name: Run docker-compose # テスト実行用にdockerを起動
        run: make docker/run

      - name: Test code
        run: go test -v ./server/handler

      - name: Stop docker-compose
        run: make docker/stop

  stg-deploy:
    name: stg-deploy
    needs: server-test
    runs-on: ubuntu-18.04
    steps:
      - uses: chrislennon/action-aws-cli@v1.1

      - name: Set AWS region
        run: aws configure set region ap-northeast-1

      - name: Run AWS CodeDeploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws deploy create-deployment --application-name "scenepicks-stg-deploy" --deployment-group-name "scenepicks-stg" --file-exists-behavior "OVERWRITE" --github-location repository="shortintern2020-C-cryptograph/TeamF",commitId=$GITHUB_SHA